# Site settings
title: The Insidious One
description: Personal Portfolio, IT Support
tagline: C/C++ Programming / Web Development / Electronics
keywords: it,personal,portfolio,project,projects,contact,library,website,web development,developing,technologies,design,art,freelance,developer,building websites,wallpaper,logo,photo,photoshop,html5,css3,javascript,3d modeling,programming,c++,cxx,c,c99,c11,cxx11,c++11,cxx14,c++14,cxx17,c++17,cxx20,c++20,cxx23,c++23,krita,blender,electronics,engine,support,quality
author: K. Petrov
slogan: Absolute Determination
first_published: 2008
email: fymfifa@gmail.com
donate_url: https://www.paypal.com/donate/?hosted_button_id=QEQLYAGDHRHUQ
#donate_url: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WMW75J9ZWHXAU

enforce_ssl: insidious-src.github.io
url: https://insidious-src.github.io
#enforce_ssl: insidious-src.online
#url: https://insidious-src.online
url_dir: /
timezone: Europe/Sofia
encoding: utf-8
permalink: /:categories/:title/
newsfeed_max: 4
google_analytics_id: UA-86048189-3

freelance_status: available
freelance_message:
    available: I am currently available for hire.
    busy: I am probably working on some project right now and can't take your order.
    away: I am not taking any orders at this time. Check back in a few days.

social:
    #twitter:
    github: https://github.com/insidious-src
    #linkedin-square:
    #facebook-official:
    #google-plus-square: https://plus.google.com/u/0/103914350235946753433
    email: fymfifa@gmail.com
    #flickr:
    #instagram:
    youtube-square: https://www.youtube.com/user/fymfifa
    spotify: https://open.spotify.com/user/fymfifa
    #stack-overflow:
    #vimeo:
    #reddit:
    #stubleupon:
    #delicious:
    #pied-piper:
    #digg:
    soundcloud: https://soundcloud.com/insidious_one
    #deviantart:
    #angellist:
    #tumblr-square:
    #stackexchange:
    #weibo:
    #trello:
    #foursquare:
    #linux:
    bitbucket: https://bitbucket.org/insidious-src/
    #vk:
    #slack:
    #vine:
    #weixin:
    #yelp:
    #skyatlas:
    #leanpub:
    #connectdevelop:
    #ils:
    #forumbee:
    #tripadvisor:
    #amazon:
    html5: https://validator.w3.org/nu/?doc=https%3A%2F%2Finsidious-src.github.io%2F
    css3: https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Finsidious-src.github.io%2F&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en#css

# Build settings
markdown: kramdown

#sass:
    #style: compressed

compress_html:
    clippings: all

relative_links:
  collections: true